name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Если ваша главная ветка называется master, замените main на master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate Static Site
        run: npm run generate

      - name: Fix Jekyll for Nuxt
        run: touch .output/public/.nojekyll # Отключает встроенный парсер GitHub, чтобы папка _nuxt не блокировалась

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public # Робот берет файлы напрямую из папки компиляции

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
